const { createClient } = require('@supabase/supabase-js');

module.exports = async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const {
    officialEmail,
    phoneName,
    phoneNumber,
    ourWA     = [],
    yourWA    = [],
    platforms = [],
    remarks
  } = req.body;

  const dashboardUrl = (process.env.VERCEL_URL_FULL || 'https://your-site.vercel.app') + '/dashboard';
  const ownerName   = officialEmail || phoneName || 'A new owner';

  // ─────────────────────────────────────────
  // ACTION 1: Save to Supabase
  // ─────────────────────────────────────────
  try {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_SERVICE_KEY
    );

    const emergencyWA = yourWA.map(function(w) {
      return { emer_name: w.name || null, emer_contact: w.number || null };
    });

    const { error } = await supabase
      .from('onboarding_submissions')
      .insert({
        official_email:   officialEmail || null,
        phone_name:       phoneName     || null,
        verification_num: phoneNumber   || null,
        our_wa:           ourWA,
        emergency_wa:     emergencyWA,
        platforms:        platforms,
        remarks:          remarks       || null
      });

    if (error) {
      console.error('Supabase save failed:', error.message);
    } else {
      console.log('Supabase save successful');
    }
  } catch (e) {
    console.error('Supabase exception:', e.message);
  }

  // ─────────────────────────────────────────
  // ACTION 2: Send email via Resend
  // ─────────────────────────────────────────
  try {
    const emailHtml = '<html><body style="font-family:Arial,sans-serif;background:#f2f0e8;padding:30px;">'
      + '<div style="max-width:600px;margin:0 auto;background:#fff;border-radius:10px;overflow:hidden;border:1px solid #ddd;">'

      + '<div style="background:#1a1a1a;padding:24px 28px;border-bottom:3px solid #c49a00;">'
      + '<p style="margin:0;font-size:11px;letter-spacing:.2em;text-transform:uppercase;color:#c49a00;">Strategy Cues</p>'
      + '<h2 style="margin:8px 0 4px;font-size:20px;color:#f0ead8;">New Onboarding Submission</h2>'
      + '<p style="margin:0;font-size:13px;color:#888;">Submitted: ' + new Date().toLocaleString() + '</p>'
      + '</div>'

      + '<div style="padding:24px 28px;">'
      + '<p style="font-size:15px;color:#1a1a1a;margin:0 0 20px;">Account details have been submitted by <strong>' + ownerName + '</strong>.</p>'

      + '<div style="background:#f5f0e0;border-radius:8px;padding:16px 20px;margin-bottom:20px;">'
      + '<p style="margin:0 0 12px;font-size:13px;color:#555;font-weight:600;text-transform:uppercase;letter-spacing:.05em;">View Full Details</p>'
      + '<p style="margin:0 0 14px;font-size:13px;color:#555;">All submitted details including platform credentials are available on the dashboard.</p>'
      + '<a href="' + dashboardUrl + '" style="display:inline-block;background:#c49a00;color:#111;padding:10px 22px;border-radius:7px;font-weight:700;font-size:13px;text-decoration:none;">Open Dashboard &rarr;</a>'
      + '</div>'

      + '<table style="width:100%;border-collapse:collapse;font-size:13px;margin-bottom:16px;">'
      + '<tr style="background:#f5f0e0;"><th colspan="2" style="padding:8px 12px;text-align:left;font-size:11px;text-transform:uppercase;letter-spacing:.05em;color:#555;border:1px solid #ddd;">Submission Summary</th></tr>'
      + '<tr><td style="padding:8px 12px;border:1px solid #ddd;font-weight:600;color:#555;width:180px;">Official Email</td><td style="padding:8px 12px;border:1px solid #ddd;">' + (officialEmail || '-') + '</td></tr>'
      + '<tr style="background:#fafaf6;"><td style="padding:8px 12px;border:1px solid #ddd;font-weight:600;color:#555;">Contact Name</td><td style="padding:8px 12px;border:1px solid #ddd;">' + (phoneName || '-') + '</td></tr>'
      + '<tr><td style="padding:8px 12px;border:1px solid #ddd;font-weight:600;color:#555;">Platforms</td><td style="padding:8px 12px;border:1px solid #ddd;">' + (platforms.map(function(p){ return p.platform; }).filter(Boolean).join(', ') || '-') + '</td></tr>'
      + '</table>'

      + '</div>'

      + '<div style="background:#1a1a1a;padding:12px 28px;font-size:11px;color:#666;">Auto-generated by Strategy Cues Onboarding Form</div>'
      + '</div></body></html>';

    const resp = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Authorization': 'Bearer ' + process.env.RESEND_API_KEY,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        from:    'Strategy Cues <onboarding@resend.dev>',
        to:      ['samruddhi.waghchaure@strategycues.com'],  // TEMP - revert after DNS verified
        subject: 'New Onboarding Submission - ' + ownerName,
        html:    emailHtml
      })
    });

    const result = await resp.json();
    if (resp.ok) {
      console.log('Email sent successfully. ID:', result.id);
    } else {
      console.error('Resend failed:', JSON.stringify(result));
    }
  } catch (e) {
    console.error('Email exception:', e.message);
  }

  // Always return success to the form — both actions are independent
  return res.status(200).json({ success: true });
};
